# Generated by roxytest: Do not edit by hand!


test_that("Function validate_input_size() @ L6", {
  expect_error(validate_input_size(1:2, 1))
  expect_error(validate_input_size("123456", 1, min_char = 7))
  expect_error(validate_input_size("123456", 1, max_char = 5))
})


test_that("Function validate_input_pattern() @ L19", {
  expect_error(validate_input_pattern("Test string", "Tast string"))
})


test_that("Function validate_input_choice() @ L30", {
  expect_error(validate_input_choice(20, 22:28))
})


test_that("Function validate_date() @ L44", {
  expect_error(validate_date(2005, day = 15))
  expect_error(validate_date(month = 5))
  expect_error(validate_date(2005, 13))
  expect_error(validate_date(2005, 10, 32))
  expect_error(validate_date(2005, -1, 6))
  expect_error(validate_date(month = 1, day = 32))
})


test_that("Function validate_dates() @ L69", {
  expect_error(validate_dates("18 MAY 2005", "17 MAY 2005"))
  expect_error(validate_dates("MAR 2005", "FEB 2004"))
  expect_error(validate_dates("2005", "2004"))
})

