# Generated by roxytest: Do not edit by hand!


test_that("Function gedcom_value() @ L232", {
  expect_equal(gedcom_value(GEDCOM_HEADER(), "HD", "FORM", 2), "LINEAGE-LINKED")
  expect_equal(gedcom_value(GEDCOM_HEADER(), "HD", "TEST", 1), "")
  expect_equal(gedcom_value(GEDCOM_HEADER(), "HD", "VERS", 2), "5.5.5")
  expect_equal(gedcom_value(GEDCOM_HEADER(), "HD", "VERS", 3), "5.5.5")
})

